### PR TITLE
Setup outline cmap correctly.

### PR DESCRIPTION
**Pull request by jamesgk**
This makes some minor adjustments to cmap creation for the intermediate outline font.

### CODE REVIEW

**Comment by anthrotype** [comment]
@typesupply could you please merge this?
It sets up the correct platform-specific encodings for format 12 cmap subtables, and also makes sure that the format 12 subtable (non-BMP) is a superset of the format 4 (BMP) one.
thank you.

**Comment by typesupply** [comment]
Oops. I thought I had merged this already.

Could someone apply the change to the ufo3 branch and submit a PR for that?

**Comment by anthrotype** [comment]
nice, thanks

**Comment by miguelsousa** [comment]
@typesupply ufo3 PR at #16

**Pull request merged**
