### PR TITLE
OTFCompiler: allow specifying a custom feature file

### PR DESCRIPTION
**Pull request by adrientetar**
Useful when you want to use a FEA that's separate from the UFO itself.

r? @typesupply

### CODE REVIEW

**Comment by adrientetar** [comment]
Just pushed a fix to this.

**Comment by typesupply** [comment]
This seems fine. I'll merge it and open an issue for it to be fixed in the ufo3 branch (unless you want to make the change there now).

**Comment by adrientetar** [comment]
> This seems fine. I'll merge it and open an issue for it to be fixed in the ufo3 branch (unless you want to make the change there now).

Maybe I'll do another PR later to merge all patches that aren't in ufo3 yet.

**Comment by typesupply** [comment]
That would be incredibly helpful. I'm overwhelmed with stuff to do right now.

**Pull request merged**
